development:
  adapter: postgresql
  encoding: unicode
  database: asn2_development
  pool: 5
  username: cmalla
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: store_test
  pool: 5
  username: cmalla
  password:

production:
